### ISSUE TITLE
.xpi appears corrupt

### ISSUE THREAD

**Issue by Mayccoll** [mozilla/FirefoxColor#636] opened 2018-12-17 14:10 UTC
Hi,
I download the .xpi file, but i was unable to installed because an error.

- A functionality that could be added would be to upload a pre-existing theme and edit from that.
The only way right now is by URL.

![fullscreen_17_12_18__9_03_am](https://user-images.githubusercontent.com/2009698/50092208-70983680-01db-11e9-81fa-fcecab49b238.png)

Thanks

**Comment by Anex007** [comment] 2019-01-23 18:52
I have the same issue i cant seem to install an add on from file_

**Comment by caitmuenster** [comment] 2019-08-05 17:32
Marking this as a p2 because it needs investigation.

**Comment by Rob--W** [comment] 2019-08-26 17:11
Which XPI file are you trying to install?

**Comment by Rob--W** [comment] 2019-08-26 17:29
@stevenengler It's indeed because themes that are downloaded in that way are not signed.

The color.firefox.com URL is the recommended way. Recently we updated Firefox Color to be compatible again with Firefox 70. Any previously shared URL has automatically been migrated, which would not be possible if themes were shared via XPIs.

**Comment by rebmullin** [comment] 2020-03-15 20:32
I *believe* we can close this one too. I believe #842 helps address this issue.

// cc @caitmuenster

**Closed** 2020-03-16 13:10 UTC
Labels: Priority: p2

**Comment by ghost** [comment] 2025-05-18 00:16
I looked at #842 but see no way to fix this. Given this is marked completed/closed perhaps a regression on 138.0.3? Any previously saved Firefox Color themes fail to work with the corruption warning.
