### ISSUE TITLE
Notification message does not point to “Share” button at click

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/FirefoxColor#878] opened 2020-01-09 14:03 UTC
[Affected versions]:
Firefox Nightly 74.0a1 

[Affected Platforms]:
All Windows 
All Mac 
All Linux 

[Prerequisites]:
Have a new Firefox profile with the latest version of the "Firefox Color" add-on  

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites. 
2. Navigate to color.firefox.com   and install Firefox Color add-on
3. Click on “Share” button from top right side of the page 
4. Observe the notification message  

[Expected result]:
Notification message points to “Share” button.

[Actual result]:
Notification message points to “Random” button.

[Notes]:
This issue is not reproducible before "Firefox Color" add-on installation. 
Attaching a screenshot with the issue.
![share-button](https://user-images.githubusercontent.com/15685960/72073825-b92b0200-32be-11ea-9609-5d5437020017.png)

**Comment by Je-ni** [comment] 2020-03-17 07:07
Helo, I want to work on this issue but I noticed that the version I pulled from master is not the same as that on the website [Here](https://color.firefox.com). My local copy doesn't have the export button. Please help.

**Comment by Rob--W** [comment] 2020-03-17 13:04
The Export button is only visible when the extension is installed:
https://github.com/mozilla/FirefoxColor/blob/31019674c050dd46ccaf6889108a408e1fa55328/src/web/lib/components/AppHeader/index.js#L149-L155

The `hasExtension` flag is set here, in response to messages from the extension: https://github.com/mozilla/FirefoxColor/blob/a43d5c66c7dc6f644f4e42e6a53ed1df9e19f099/src/web/index.js#L180

To start Firefox with the extension installed, you can use the `npm run` command, which triggers this handler: https://github.com/mozilla/FirefoxColor/blob/a43d5c66c7dc6f644f4e42e6a53ed1df9e19f099/package.json#L48

**Comment by Je-ni** [comment] 2020-03-17 14:21
It seems the content of the tree you referenced is different from that of the master branch.
https://github.com/mozilla/FirefoxColor/blob/41ef6ef3a25897c347e1912800ac7275c6a98c65/package.json#L21

**Comment by Rob--W** [comment] 2020-03-17 14:52
The contents of the line that I referenced is still on the master branch: https://github.com/mozilla/FirefoxColor/blob/a43d5c66c7dc6f644f4e42e6a53ed1df9e19f099/package.json#L48

I'm intentionally including the specific revision, so that even if the file changes, the intended content is still shown.

PS. In case you're wondering about which branch is used for the production website, see https://github.com/mozilla/FirefoxColor#environment-list

**Comment by Je-ni** [comment] 2020-03-17 21:47
Hello @Rob--W, please assign this task to me. I've gotten it setup.

**Comment by caitmuenster** [comment] 2020-03-17 21:59
Hey @Je-ni! Once you submit a PR we'll assign this issue to you. :)

**Comment by Je-ni** [comment] 2020-03-17 22:19
Please review the PR.

**Comment by ValentinaPC** [comment] 2020-04-03 06:15
I have verified the issue, and it is **still reproducible**, using Firefox Nightly 76.0a1 ( Build ID20200402095145) on -stage (https://color.stage.mozaws.net/) and -dev (https://mozilla.github.io/FirefoxColor/) by updating the add-on to point to these environments in Windows, Mac and Linux.

The Share notification message, still points to “Random” button.

![share](https://user-images.githubusercontent.com/15685960/78329918-7611bf80-758b-11ea-9319-a9a665d3ef9d.png)
.

**Comment by rebmullin** [comment] 2020-04-07 00:38
This fix has not been pushed to stage yet. I am going to close this and I can reassign it to you when it's ready. What is the best way to do that?

**Closed** 2020-04-07 00:38 UTC
Labels: [QA]:Minor issue

**Comment by rebmullin** [comment] 2020-04-14 01:22
#899 has been deployed to stage so okay to recheck this when you can. thanks!

**Comment by SoftVision-SimonaRosu** [comment] 2020-05-04 15:16
I have verified this issue on the stage server of the Firefox Color website and is no longer reproducible. Tested using the latest Nightly 77.0a1 (Build ID: ), Firefox RC 76 (Build ID: 20200427162639), Firefox Release 75 (Build ID:) on Windows 10 x64, Ubuntu 18.04 x64, Mac 10.14.6.
- The Share notification message points to the “Share” button. 

However, the issue is still reproducible with the production version. Can you please confirm if the fix wasn’t deployed to prod?
