### ISSUE TITLE
Color values tend to differ slightly

### ISSUE THREAD

**Issue by FayneAldan** [mozilla/FirefoxColor#158] opened 2018-03-11 05:40 UTC
How to reproduce:
1. Go to any color option and set the hex to `800080`
2. Observe that the blue value is set to `127`, even though `0x80` should be `128`
3. Switch to any other textbox
4. The hex changes from `800080` to `80007F`

In addition, when clicking any of the colors in the default palette (except `000000`, `4A4A4A`, and `FFFFFF`), the color is changed after a short moment (once the color is applied to the actual theme). However, being able to notice this behavior might depend on computer performance (or just comparing the set value to the original specified in the code).

**Comment by johngruen** [comment] 2018-04-17 15:12
#226 might be a dupe of this

**Comment by johngruen** [comment] 2018-04-18 11:51
@lmorchard wfm

**Closed** 2018-04-20 19:04 UTC
Labels: has pr, mvp
