### ISSUE TITLE
[nice to have] Default alignment of custom background should be aligned right

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/FirefoxColor#514] opened 2018-10-11 22:15 UTC
This is a request from one of our power theme designers who noted that she had a hard time finding the focal point of her uploaded custom background image because it aligned left and she was expecting it to align right. 

Here's what she saw when she first uploaded her image: 

![colors1](https://user-images.githubusercontent.com/23342476/46836945-515ad400-cd68-11e8-93c6-71bf2617d8e4.jpg)

Here's what happened after she figured out she needed to align it to the right: 
![colors2](https://user-images.githubusercontent.com/23342476/46836953-5d469600-cd68-11e8-900e-914acd726be0.jpg)

I don't think that this should block graduation for Fx Color, but it is something we should take a closer look at for upcoming versions.

**Comment by lmorchard** [comment] 2018-10-12 14:19
Duplicate of #499 I think

**Closed by lmorchard** 2018-10-12 14:19 UTC
