### ISSUE TITLE
The "Save" button is wrongly active on all saved themes except the last

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/FirefoxColor#311] opened 2018-05-30 11:49 UTC
**[Affected versions]:**
- Firefox 60.0.1 and above

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a new Firefox profile with the latest version of the "Firefox Color" add-on (0.0.39 custom built on 30.05.2018) installed.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and save at least two themes.
2. Click on each saved theme from the "Saved themes" area and observe the "Save" button status.

**[Expected result]:**
- The "Save" button is deactivated on each saved theme.

**[Actual result]:**
- The "Save" button is deactivated only on the last saved theme and it is active on the other ones.

**[Notes]:**
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/40718395-7804034c-6418-11e8-918b-2237aa02008e.gif)

**Comment by Softvision-MariusComan** [comment] 2018-10-04 08:39
This issue is still reproducible with the latest version of the "Firefox Color" add-on (2.0.0) installed from Test Pilot.

**Comment by rebmullin** [comment] 2020-04-25 20:06
The ui has changed but there was a similar issue with the new UI (see #886). This  should be fixed on stage. Please reopen if you see something different.

**Closed by rebmullin** 2020-04-25 20:06 UTC
Labels: Priority: p3, [QA]:Normal issue

**Comment by SoftVision-SimonaRosu** [comment] 2020-05-04 15:18
I have verified this issue on the stage server of the Firefox Color website and is no longer reproducible. Tested using the latest Nightly 77.0a1 (Build ID: 20200504093644 ), Firefox RC 76 (Build ID: 20200427162639), Firefox Release 75 (Build ID:) on Windows 10 x64, Ubuntu 18.04 x64, Mac 10.14.6.
- The ”Save” button is changed to “Saved!” grayed out button when a theme is saved. 

However, the issue is still reproducible with the production version. Can you please confirm if the fix wasn’t deployed to prod?

**Comment by caitmuenster** [comment] 2020-05-04 22:35
Thanks @SoftVision-SimonaRosu! Correct, this hasn't been deployed to prod yet. Glad to know it's fixed on stage.
