### ISSUE TITLE
Improper display of title bar buttons in no-titlebar view

### ISSUE THREAD

**Issue by stlaz** [mozilla/FirefoxColor#346] opened 2018-06-07 07:15 UTC
Hello,
It would seem that Color breaks the display of the title bar icons when the title bar is hidden. This behavior was observed on Fedora 28, GNOME with Fx Color (github) 1.0.1.

Adding a screenshot where the minimize/maximize/close buttons are compared when Color is disabled/enabled.
![improperly displayed buttons](https://image.ibb.co/d9XSco/ff_color_bug.png)

**Comment by Softvision-AndreeaCupsa** [comment] 2018-06-08 11:09
As I don't have Fedora 28, GNOME desktop environment I tested this issue on Fedora 28, Ubuntu 16.4, Linux Mint 18.3, Argentos, and Debian GNU/Linux(9.4) on Firefox Release (60.0.2) and Firefox Nightly (62.0a1) with Firefox Color(1.0.1) installed from https://color.firefox.com/ , and I cannot reproduce it. 
Can you tell me if you have a custom environment?

**Comment by stlaz** [comment] 2018-06-08 11:53
I am currently using firefox-60.0.1-6.fc28.x86_64 from the updates repository. I use a custom GNOME theme  called Arc, yet this one does not cause problems w/o Color (I tried installing the same Color version you're using to make sure the failure persists - it does).

When you were testing this on Fedora 28 (if I understand your comment correctly, you did), have you used Wayland or Xorg as the display client?

**Comment by Softvision-AndreeaCupsa** [comment] 2018-06-08 14:42
My mistake, it is Fedora 27 and the display client is Wayland.
Unfortunately I haven't managed to install the Arc Theme on Fedora 27 due to some errors. But, I have managed to install it on Ubuntu 16.04 and tried all the modes (arc, dark arc, light arc etc.) and I cannot reproduce this issue.
However, can you please tell me how did you installed Arc Theme on Fedora 28.

**Comment by stlaz** [comment] 2018-06-10 19:14
Sorry, I did not get to this earlier. I wanted to reproduce this issue on my other machine with Fedora 27, yet when I tried to hide the title bar, the issue appeared even w/o the Firefox Color installed. Not even Fedora 28 upgrade helped there.
All the above leads me to suspect that there's probably some Firefox display bug which is hard to encounter as it may be triggered by upgrades from older system versions (and thus old configuration files being in place).
You may probably close this issue for now since it may not necessarily be a problem with Firefox Color. I'll be reinstalling one of those failing systems in under a month and will reopen this should it reoccur 🙂

**Comment by Softvision-AndreeaCupsa** [comment] 2018-06-11 11:32
Based on the last comment and considering the fact that this is not a Firefox Color issue, I will close it.
@stlaz if you still reproduce the issue after reinstalling the system, you can log it in Bugzilla: https://bugzilla.mozilla.org/

**Closed by Softvision-AndreeaCupsa** 2018-06-11 11:32 UTC
