### ISSUE TITLE
Alpha value textbox incorrect after first removing focus

### ISSUE THREAD

**Issue by FayneAldan** [mozilla/FirefoxColor#159] opened 2018-03-11 06:02 UTC
Steps to reproduce:
1. Open the Themer webpage. If already open, refresh the page.
2. Click Toolbar Color or Search Bar Color.
3. Use the alpha **slider** to change the alpha value (preferably by a noticeable amount, such as from 100% to 0%).
4. Click the alpha value **textbox** then remove focus (click anywhere else).
5. The value in the textbox will update to match the original value (from when the page was opened).

![](https://i.imgur.com/XfSCh1T.gif)

**Comment by shr7** [comment] 2018-03-15 23:52
@johngruen This seems to be a problem for all the editable components, not just alpha :/

**Comment by johngruen** [comment] 2018-04-17 15:13
#226

**Comment by lmorchard** [comment] 2018-04-17 20:02
Having trouble reproducing this one. The one thing I can make happen is 1) focus the alpha text field; 2) move the alpha slider; 3) the text field doesn't update to the correct value until it loses focus. But, I think that's just how React handles text fields - i.e. doesn't update them when they have focus.

But also, that doesn't seem to be the behavior happening in the gif.

**Comment by lmorchard** [comment] 2018-04-20 19:15
Going to close this for now. We reworked a lot of the state behind this, and I can't seem to reproduce it anymore. Let's reopen if it looks easily reproducible again.

**Closed by lmorchard** 2018-04-20 19:15 UTC
Labels: has pr, mvp
