### ISSUE TITLE
A few color picker panels are wrongly displayed outside the viewport when the browser is resized 

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla/FirefoxColor#247] opened 2018-04-20 14:31 UTC
**[Affected versions]:**
- Firefox 59.0.2 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**

- Have a Firefox profile with the latest version of the "FirefoxColor" add-on (0.0.35 custom build)
installed from the "about:debugging" page.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Click the "Firefox Color" toolbar button.
3. Resize the page to 1/2 size.
4. Click the "Toolbar Color" bubble.
5. Observe the opened color picker panel position.

**[Expected result]:**
- Panel is fully visible. 

**[Actual result]:**
- Left part of the panel is cut off and is not visible. 

**[Notes]:**
- "Toolbar Icons and Text" and "Background Color" panels are also affected by this issue. 
- The same panels are affected when the browser is resized to 1/2 or less of the browser's full size. 
- This issue is also reproducible if the color picker panel is opened before resizing. 
- Attached a screen recording of the issue:
![resizing the browser](https://user-images.githubusercontent.com/37875464/39056885-882e9c22-44c0-11e8-8933-efcee5dbdb49.gif)

**Comment by johngruen** [comment] 2018-05-08 15:18
Dupe of #199

**Closed by johngruen** 2018-05-08 15:18 UTC
