### ISSUE TITLE
Install Themer banner is briefly displayed when the page is refreshed

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/FirefoxColor#169] opened 2018-03-14 13:46 UTC
**[Affected versions]:**
- Firefox 58.0.2 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Themer" add-on (0.0.30 custom build) installed from the "about:debugging" page.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Click the "Themer" toolbar button.
3. Refresh the page and observe the behavior.

**[Expected result]:**
- The page is correctly refreshed.

**[Actual result]:**
- When the page is refreshed, the install themer banner is briefly displayed at the top of the page.

**[Notes]:**
- Attached a screen recording of the issue: 
![install banner](https://user-images.githubusercontent.com/19226534/37405780-3ba5a380-279e-11e8-867e-f3d5cc754e27.gif)

**Comment by johngruen** [comment] 2018-03-14 14:58
Yeah i've been thinking about this one, and we might be best served by not having this banner move page content up or down so that even if it flashes the content doesn't jump

**Comment by lmorchard** [comment] 2018-03-14 15:02
This is also where the loader is kind of a guess - could be fixed by increasing the loader wait, since this stuff is unpredictable based on performance where it's run

**Comment by Softvision-AndreeaCupsa** [comment] 2018-05-04 11:42
This issue is still reproducible on latest Firefox (59.0.3) and latest Nightly (61.0a1) with Firefox Color(0.0.35) installed, on Win10 x64 and Mac 10.13.3. When refreshing the page "Install Themer" banner is briefly displayed.

**Comment by johngruen** [comment] 2018-05-04 14:10
I have a feeling this is because we haven't done a deployment recently.

**Comment by lmorchard** [comment] 2018-05-04 16:28
Well, a deployment won't affect localhost either way. Probably still just going to show this banner on some machines unless we keep bumping the loader delay up

**Comment by Softvision-AndreeaCupsa** [comment] 2018-05-07 13:47
This issue is still reproducible on Win 10 x64, Mac 10.13.3 and Arch Linux, using latest Firefox (59.0.3) and latest Nightly (61.0a1) with Firefox Color (0.0.36) installed. The banner is still briefly displayed when refreshing the page and also when you navigate to Firefox Color site.

**Comment by lmorchard** [comment] 2018-05-08 14:57
Unassigning myself for now, because I'm not actively working on it at the moment. Will probably get back to looking, but didn't want to block

**Comment by Softvision-AndreeaCupsa** [comment] 2018-05-08 15:37
Attached the screenshot with the behaviour of the issue:

![install themer banner](https://user-images.githubusercontent.com/37875464/39767169-c0901884-52ee-11e8-9a83-a8c0777cd31c.gif)

**Comment by lmorchard** [comment] 2018-05-08 16:02
Huh, that really looks weird - like the loader isn't spinning at all on a click from the toolbar

**Comment by Softvision-AndreeaCupsa** [comment] 2018-05-16 12:08
After the position of the banners was updated, I tested this on Win 10 x64, Mac 10.12 with the latest Firefox Color version (0.0.37) when refreshing the page the "Install Firefox Color" banner is briefly displayed in "Share your theme" + "Save your theme" section. 
Because of this, the "Feedback" button and "Share your theme" + "Save your theme" section are displayed with a delay.
I am attaching a screen recording of the issue:

![screen recording of the issue](https://user-images.githubusercontent.com/37875464/40115990-f4de510a-591a-11e8-9d2a-3786712a5f09.gif)

**Comment by lmorchard** [comment] 2018-05-22 15:39
I just noticed this line we added [a month or so ago](https://github.com/mozilla/FirefoxColor/blame/master/src/web/index.js#L33):

```javascript
// If dev show right away to make debugging faster
const LOADER_DELAY_PERIOD = process.env.NODE_ENV === "development" ? 0 : 2000;
```

This means that the delay has been disabled altogether on a local copy of the site and the github pages dev deployment. So, that would explain why the loader isn't waiting around at all.

**Closed** 2018-05-22 16:26 UTC

**Comment by Softvision-AndreeaCupsa** [comment] 2018-05-23 10:43
I have verified this issue and is no longer reproducible on Mac 10.13 and Windows 10 x64 on latest Firefox (60.0.1) and latest Nightly (62.0a1) with latest "Firefox Color" (0.0.39 23/05/2018) installed. The "Install Themer" banner is no longer briefly displayed when navigating to the "Firefox Color" page or when refreshing it.
