### ISSUE TITLE
Theme URL is wrongly selected when clicking inside the "Share your theme" text div

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla/FirefoxColor#251] opened 2018-04-23 16:20 UTC
**[Affected versions]:**
- Firefox 59.0.2 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**

- Have a Firefox profile with the latest version of the "FirefoxColor" add-on (0.0.35 custom build)
installed from the "about:debugging" page.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Click the "Firefox Color" toolbar button.
3. Click inside the "Share your theme" text div area.

**[Expected result]:**
- Nothing happens.

**[Actual result]:**
- The text inside the URL field is being selected.

**[Notes]:**
- Attached a screen recording of the issue:
![click selects](https://user-images.githubusercontent.com/37875464/39139598-00cfea02-472b-11e8-9be3-08b7f30e23c3.gif)

![url copy](https://user-images.githubusercontent.com/37875464/39139616-10635238-472b-11e8-8df4-667a61e8f37d.jpg)

**Comment by johngruen** [comment] 2018-05-16 14:50
I think this works as intended, closing

**Closed by johngruen** 2018-05-16 14:50 UTC
