### ISSUE TITLE
Download image file of saved themes

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/FirefoxColor#485] opened 2018-10-02 22:14 UTC
Some users have asked for the ability to download a file of their saved theme from Color to keep a local copy. 

This may be related to users wanting to be able to upload their saved themes from Color to AMO for wider distribution. Flagging this as a question for user outreach as I'm not if there are plans to submit themes created by Color to AMO. cc: @jorgev

**Comment by lmorchard** [comment] 2018-10-03 16:15
Yeah, we should flesh out the exact use cases for this. To be pedantic, everything is in localStorage, there's no server from which to download the themes.

So maybe more specifically the ask is: A feature to export to a portable file for backup, along with an import feature to load those themes onto another machine? Possibly even as a submission to AMO?

Also feels related to issues #93 and #94, which are about exporting static themes and submitting presets back to Color.

**Comment by caitmuenster** [comment] 2018-10-03 20:06
Thanks, @lmorchard! It looks like the primary use case here is to export the theme for submission to AMO. One of our more prolific theme designers wants to be able to preview/tweak themes in Color, finalize the theme, and then make the theme available on AMO.

**Comment by lmorchard** [comment] 2018-10-03 21:55
> primary use case here is to export the theme for submission to AMO.

Cool! That's basically where we wanted to head with #93. 

I need to revisit the work, but I worked with an intern over the summer to explore building a microservice in AWS Lambda that would accept a theme submission from Color, convert it to a proper theme add-on, and respond with a `.xpi` download.

Whether that exact thing can work for an AMO submission, I don't know, but we can explore something similar.

**Comment by atsay** [comment] 2018-10-03 21:57
To get a little meta (for background), currently the primary use case we have for Color is to support some of the developer features we lost when Personas Plus went away. Preview, image support, and the ability to save or export the image or xpi file are the basic functions a theme designer would need.

**Comment by johngruen** [comment] 2018-10-16 15:11
We are working on an export feature now. I am gonna close this as a dupe of #93

**Closed by johngruen** 2018-10-16 15:11 UTC
