### ISSUE TITLE
sendEvent to google-analytics.com/collect gets blocked because of CORS

### ISSUE THREAD

**Issue by digitarald** [mozilla/FirefoxColor#342] opened 2018-06-05 20:23 UTC
STR:
- Open https://color.firefox.com/
- Click `Install Firefox Color`
- `sendEvent` is triggered
- Observe Console

Fails with:

`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://www.google-analytics.com/collect. (Reason: CORS request did not succeed).`

This error does not show up with adblockers, as they catch the request before it goes out.

**Comment by lmorchard** [comment] 2018-06-05 20:57
This sounds like a dupe of https://github.com/mozilla/FirefoxColor/issues/256

**Comment by digitarald** [comment] 2018-06-05 21:03
This is from a fresh profile, without adblockers

**Comment by lmorchard** [comment] 2018-06-06 15:42
> This is from a fresh profile, without adblockers

I can't reproduce this on a fresh profile in Fx 60.0.1, Dev Edition 61.0b11, or Nightly 62.0a1. The only time I see this error is if I enable uBlock Origin 1.16.8.

Can you share any other details about what version you're using, etc?

**Comment by digitarald** [comment] 2018-06-06 18:49
Reproduced again on `62.0a1 (2018-06-06) (64-bit)`

**Comment by lmorchard** [comment] 2018-06-07 19:48
I'm kind of stumped - I still can't reproduce in any version / channel with a fresh profile :(

**Comment by Softvision-AndreeaCupsa** [comment] 2018-06-08 11:30
I can reproduce this issue on Windows 10 64bit, Mac 10.13 and Arch Linux on Latest Nightly (62.0a1 (2018-06-07)) following the steps from the initial comment. 
Using a new profile, the following error: "Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://www.google-analytics.com/collect. (Reason: CORS request did not succeed)" is displayed in the browser console.

This seems to be influenced by wether the "Send websites a “Do Not Track” signal that you don’t want to be tracked" option from "about:preferences#privacy" is set as "Always".

I attached a screen recording of the issue:

![rec of issue - cors error](https://user-images.githubusercontent.com/37875464/41155906-6cb698ee-6b28-11e8-98bb-60e6d7a2cb0b.gif)

**Comment by johngruen** [comment] 2018-06-19 15:14
@digitarald do your new profiles spin up with DNT set to always?

**Comment by JAYNE307** [comment] 2020-04-22 08:14
Latest

**Comment by Rob--W** [comment] 2021-03-15 16:23
Duplicate of #256, but already fixed by #784 by removal of GA.

**Closed by Rob--W** 2021-03-15 16:23 UTC
Labels: Priority: p3, [QA]:Other issue, bug
