### ISSUE TITLE
The "Copied" button is wrongly changed back to "Copy" if the same preset/saved theme is selected

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/FirefoxColor#281] opened 2018-05-09 15:13 UTC
**[Affected versions]:**
- Firefox 60.0 and above

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have the latest version of the "Firefox Color" add-on (0.0.36 local-dev custom built on 09.05.2018) installed.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Click on any preset/saved theme and click the "Copy" button.
3. Click the same theme again.
4. Observe the string displayed on the "Copy" button.

**[Expected result]:**
- The "Copied" string is still displayed.

**[Actual result]:**
- The "Copy" string is displayed.

**[Notes]:**
- Based on [comment 1](https://github.com/mozilla/FirefoxColor/issues/228#issuecomment-380886470) from issue #228, the displayed string should be changed only when the URL is different or after the theme is changed. 
- Attached a screen recording of the issue: 
![rec of the issue](https://user-images.githubusercontent.com/31243259/39822903-7cb5955a-53b4-11e8-8d42-4cebeb199e04.gif)

**Comment by rebmullin** [comment] 2020-03-15 20:36
it seems the ui has changed a bit since this issue was opened. IMO this is okay currently and we can close this.

// cc @caitmuenster

**Comment by caitmuenster** [comment] 2020-03-19 22:02
@rebmullin I wasn't able to reproduce this. I'm ok with closing it.

**Closed** 2020-03-19 23:38 UTC
Labels: Priority: p3, [QA]:Minor issue

**Comment by Softvision-MariusComan** [comment] 2020-04-02 13:34
I can confirm that this issue is no longer reproducible since the UI has been changed. Considering this I am marking this issue as VERIFIED.
