### ISSUE TITLE
Entire UI turns black in Firefox 61.0b3

### ISSUE THREAD

**Issue by jamesgecko** [mozilla/FirefoxColor#282] opened 2018-05-10 14:20 UTC
I recently disabled and re-enabled this extension. Upon re-enabling, all the browser chrome has turned black. Changing options on the color picking website doesn't change any colors in the browser chrome from black.

Firefox Developer Edition 61.0b3 (64-bit)
MacOS 10.13.4 (17E202)
MacBook Pro (Retina, 15-inch, Mid 2015)

<img width="1081" alt="screen shot 2018-05-10 at 10 09 21 am" src="https://user-images.githubusercontent.com/44252/39873953-69d2e5e2-543a-11e8-9775-8497b1844f45.png">

**Comment by lmorchard** [comment] 2018-05-10 16:39
You might try uninstalling and re-installing the extension, not just disabling / enabling. We've made a number of big changes to things, but haven't had an updateURL setup with the add-on yet. So it's likely you haven't gotten an up-to-date version

**Comment by johngruen** [comment] 2018-05-11 13:45
I got another report of this recently. we should keep track as we get ready to GTM...i do have a feeling this has to do with finally adding an update URL tho

**Comment by lmorchard** [comment] 2018-05-11 16:06
Yeah, I *think* the cause here is the conversion from HSLA to RGBA. If the add-on isn't updated with code to use RGBA, all the colors are black because the HSLA values are all null

**Comment by wresuolc** [comment] 2018-05-16 15:11
If anyone encounters this again, please comment

**Comment by jamesgecko** [comment] 2018-05-16 17:56
Installing the add-on resolved this for me today.

I have all my add-ons set to manual update. Six days ago I ran into an issue where clicking update on the list removed this add-on from the list of installed add-ons. I assumed that it had been uninstalled somehow, but the add-on installation process from the theme customization website failed with an error. I know this is super vague, but I'm not sure how to reproduce it. Sorry!

**Comment by wresuolc** [comment] 2018-05-17 23:58
No worries, thanks for getting back to us.  I'll close this.

**Closed by wresuolc** 2018-05-17 23:58 UTC
