### ISSUE TITLE
No option to change inactive/background tabs color 

### ISSUE THREAD

**Issue by gaby2300** [mozilla/FirefoxColor#815] opened 2019-07-23 18:13 UTC
1) Install Firefox Color
2) Notice the absence of the option to change inactive/background tabs color

Expected result: there should be an option to change the inactive/background tabs color (there was before), mine where green

Actual result: No option to change inactive/background tabs color. They are white and there's no way to change its color

**Comment by jtg567** [comment] 2019-07-23 18:19
I'm on Nightly and disabled Firefox Color today after finding the inactive/background tabs were white.

**Comment by gaby2300** [comment] 2019-07-23 19:45
I saw this a few days ago though. I couldn't connect to IRC's #addons
channel and no one seemed to know who to contact. It was just today that I
remembered Slack and pasted this issue there.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by caitmuenster** [comment] 2019-08-07 15:22
This is caused by #763. Closing this comment out as a duplicate. :)

**Closed by caitmuenster** 2019-08-07 15:22 UTC

**Comment by caitmuenster** [comment] 2019-08-07 16:25
Hi all, this is related to #763. Closing this issue as a duplicate.
