### ISSUE TITLE
Autoscroll is wrongly activated when the "Privacy"/"Terms" links are clicked using the scroll wheel

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/FirefoxColor#335] opened 2018-06-05 15:36 UTC
**[Affected versions]:**
- Firefox 60.0.1 and above

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a new Firefox profile with the latest version of the "Firefox Color" add-on (1.0.1 custom built on 05.06.2018) installed.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and click the "Firefox Color" toolbar button.
2. Middle-click the "Privacy" button and observe the behavior.

**[Expected result]:**
- The "Terms & Privacy" pop-up is displayed.

**[Actual result]:**
- The page auto-scroll is activated and the "Terms & Privacy" pop-up is displayed.

**[Notes]:**
- This issue is not reproducible if the middle-click is performed on the "Legal", "About Test Pilot", "Cookies" or on the "Uninstall" buttons instead. In those cases, the websites are opened in a new tab.
- This issue is reproducible on Mac only if you have a mouse with a scroll wheel.
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/40986591-48b47b72-68ef-11e8-8e17-bb320711de51.gif)

**Comment by knrt10** [comment] 2018-07-14 15:21
I would like to work on this issue.

**Comment by Je-ni** [comment] 2020-03-05 23:37
Hi, I would like to work on this issue if it's not been resolved. I'm from Outreachy.

**Comment by caitmuenster** [comment] 2020-03-06 21:29
Hi @Je-ni, welcome! @Rob--W can help mentor this bug.

**Comment by Rob--W** [comment] 2020-03-08 18:44
Although I cannot reproduce the original issue, there are still bugs with the "Privacy" link.

When I follow the steps to reproduce, the Firefox Color page is opened in a new tab (because opening a link in a new tab is the default behavior for mouse-wheel-clicking on a link), but there is no information about the privacy policy. This should be fixed by treating middle-mouse click as a left-click (=normal clicking on a link).

Now, when I resize the window to make it smaller, scroll down and click on the "Privacy" link, then I see the reported issue: The privacy dialog is shown, and the page jumps to the top.

This issue is because the link is an [in-page link](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#Linking_to_an_element_on_the_same_page) (if you hover over the link, you can see that the link ends with `#`). `#` is often used as a dummy value, to get a link element to have the link appearance, without navigating away from the current page when the user clicks on it. As you can see from this bug report, using `#` has the side effect of jumping to the top of the page.

To fix this problem, you need to find where the click on the link is handled, and use [`event.preventDefault()`](https://developer.mozilla.org/en-US/docs/Web/API/Event/preventDefault) to prevent the default behavior (=jumping/navigating to the top of the page) from occurring. The `click` handler appears to be defined here: https://github.com/mozilla/FirefoxColor/blob/17a2fdacd04eefb45c27dc6910de0d089bcd6669/src/web/lib/components/AppFooter/index.js#L33

@Je-ni Feel free to ask questions if you still have them after reading my comment.

**Comment by Je-ni** [comment] 2020-03-09 20:55
Hi, I keep getting this error on npm start: 
`ERROR in ./src/images/onboarding.png
    Module build failed (from ./node_modules/image-webpack-loader/index.js):
    Error: 'C:\Users\CHIDERA\Desktop\FirefoxColor\node_modules\pngquant-bin\vendor\pngquant.exe' is not recognized as an internal or external command,
    operable program or batch file.`

I'm using Windows 10.

**Comment by Rob--W** [comment] 2020-03-10 18:47
How did you set up your local development environment? Simply `npm install` ?

**Comment by Je-ni** [comment] 2020-03-10 20:34
Yes. I did npm install then npm start. Then I kept getting errors about several commands not being a recognized command. I had to start installing each of those modules individually. Till I got to the one above.

**Comment by Rob--W** [comment] 2020-03-10 21:45
> Then I kept getting errors about several commands not being a recognized command. I had to start installing each of those modules individually. Till I got to the one above.

It sounds like your local setup went wrong. What are the versions of `node` and `npm` that you are using? What shell are you using?

If you are stuck, could you try removing the `node_modules/` directory, run `npm install` again, and share the full output? Either by attaching it as a file here, or by mailing it to me.

**Comment by Je-ni** [comment] 2020-03-11 17:32
Hello @Rob--W I sent a PR for this issue here #897

**Closed** 2020-03-16 17:13 UTC
Labels: Priority: p4, [QA]:Minor issue, good first issue, skill:js

**Comment by Softvision-MariusComan** [comment] 2020-04-02 11:48
I have verified that this issue is no longer reproducible with the latest version of the "Firefox Color" add-on (2.1.5) installed. Verified on Windows 10 x64, Ubuntu 18.04.1 x64 and Mac 10.15.4 with the latest Firefox Release (74.0 Build ID: 20200309095159) and Firefox Nightly (76.0a1 - Build ID 20200401212659) installed.
