### ISSUE TITLE
"Saved themes" tab on editing website website covered up by popup preview

### ISSUE THREAD

**Issue by TheHarmonicRealm** [mozilla/FirefoxColor#980] opened 2021-06-03 04:08 UTC
I'm using a 1080p screen on a computer running Windows 10 and this also happens on a 1440p screen on a Mac.

The "saved themes" tab on the right is always covered up by the shape representing the popup menu when I have the window:

![image](https://user-images.githubusercontent.com/44441682/120585280-52901200-c3e6-11eb-9e51-e50bd5402179.png)

Even when I have the taskbar hidden so the browser has as much vertical space as possible the button is almost completely covered up by it:

![image](https://user-images.githubusercontent.com/44441682/120585406-8834fb00-c3e6-11eb-890c-f56b5c51b78e.png)

Please fix this. Thanks!

**Comment by Rob--W** [comment] 2021-06-03 09:11
Duplicate of #952 (will be fixed with the next push)

**Closed** 2021-06-03 09:11 UTC
Labels: duplicate
