### ISSUE TITLE
latest firefox nightly update breaks "background color"

### ISSUE THREAD

**Issue by shmediaproductions** [mozilla/FirefoxColor#814] opened 2019-07-20 00:51 UTC
no matter what I set the color to it just overwrites the default theme (and custom CSS) with white for all the elements covered by "background color"
edit: specifically, these are showing up (only) when the add-on is activated now.
```
--lwt-accent-color: white;
--lwt-text-color: rgba(0, 0, 0);
```
so i guess nightly changed something relative to the theme API? is there any way to just disable certain variables that firefox color changes? unrelated, but it would be nice to know if firefox color has its own specific variable definitions that can be updated or if it just uses preexisting definitions from the API. i didn't see any in the source code, though i didn't look all that hard. and by definitions i just mean lower level than the abstraction layers you can colorize in the GUI. like do those variables map 1:1 to the variables in browser.css or global.css, or do they circumvent the variables and colorize the elements directly? i would assume that kind of specificity would cause a lot of problems with browser updates, but then i don't know what else would cause firefox color to break on a specific element when that element's variable has remained exactly the same. so in some sense it's exactly what seems to have happened here.

a temporary fix should be...
```
:root {
    --lwt-accent-color: #whatever !important;
    --lwt-text-color: #whatever !important;
}
```

remains to be seen how many other elements or variables could be broken, there are a lot of popups and context menus i can't open on command to check. but i'll post in here if i notice anything else. thanks!

**Comment by Errolyn** [comment] 2019-07-20 21:40
I check this on both Mac and Windows versions of nightly and have the same issue. Patterns still work.
![firefoxcolorissue](https://user-images.githubusercontent.com/1214589/61584427-4bb2cb80-aafc-11e9-8031-9016f7814c8b.PNG)

**Comment by shmediaproductions** [comment] 2019-07-21 00:09
That makes sense, I didn't try patterns but I went through most of the navbar elements last night and I didn't see anything changed except root and theme variables. I forgot that it even allowed patterns but I assume it probably implements the patterns with background-image? So it makes sense if the patterns still show since I don't think any background properties are changed, just where background-color is defined as var(whatever) there are apparently 2 cases where that variable's definition is being changed but not consistently with the definition in the user's firefox color theme. So the first place I'd look if I knew what I was doing is at the variable definitions from the theme api. I guess the developers of firefox color would probably already be aware of this but development doesn't seem very active.

I really hope this doesn't end up as just an abandoned experiment. It should be a built-in feature of firefox, not even an extension imo since that causes the colors to not load immediately. Like when you start up firefox it first loads the built-in theme or whatever custom CSS you have, then loads the firefox color theme on top of it. I figured that's unavoidable with an extension. If it was just built-in then it could load immediately. And could still be opt-in, just leave everything the same but in the customize page, there's a context menu where you can change the built-in theme to something else. Just put an item in that list which enables firefox color and make the extension page a chromeUI page. I get the impression that the average browser user does want to customize the UI, yet it's always considered a 'power user' feature or something. There are so many threads on reddit asking how to customize browsers, so many suggested searches, so many articles, clearly this kind of thing is in high demand. Firefox having a customization GUI built-in would be a huge and clear advantage over chrome and edge, so it's strange that mozilla does not seem to be seriously pursuing that when it's already basically been programmed in this lightweight extension.

**Comment by nt1m** [comment] 2019-07-22 02:20
See https://bugzilla.mozilla.org/show_bug.cgi?id=1567684 and https://bugzilla.mozilla.org/show_bug.cgi?id=1472740

**Comment by nt1m** [comment] 2019-07-22 02:26
This is basically broken because Firefox Color seems to still use some deprecated theme properties that now have new names.

There was a work in progress by @mgillespy regarding this, but it was never merged: https://github.com/mgillespy/FirefoxColor/tree/763-update-deprecated-properties

**Comment by impearker** [comment] 2019-07-22 14:03
I can confirm the same issue is happening for me on nightly on Windows 10(current stable), Linux(Ubuntu 19.04), and Mac Mojave. Please let me know if there are logs or anything I can add to help address this issue.

**Comment by shmediaproductions** [comment] 2019-07-23 01:11
> 
> 
> I can confirm the same issue is happening for me on nightly on Windows 10(current stable), Linux(Ubuntu 19.04), and Mac Mojave. Please let me know if there are logs or anything I can add to help address this issue.

I don't think so, it doesn't seem to return any errors. You could paste your values for the variables that are missing now, and the source stylesheet for the prevailing rule. They always show up on the main window element in the inspector. The extension's variable changes show up under element {}, the rule at the top.
![firefox color bug](https://user-images.githubusercontent.com/33384265/61674971-2a441200-acab-11e9-82b2-c09754f5f387.png)
Mine are just crossed out because I moved most of the variables into my own css file. But you can see how it says white with black text even though firefox color's settings are #080B21 with white text.

Thanks for sharing that nt1m, I will compare the changes and try to see if it's complete.

**Comment by shmediaproductions** [comment] 2019-07-23 01:33
It just occurred to me that I can only install the build temporarily with the built in scripts. If I try a permanent install, since I can't control the circleci deployment or the main github site, I think I will lose all the changes to the web editor so the new properties are left without values.

@mgillespy thanks for updating this extension, do you know if there's any way to get it running locally permanently? Or if anyone is still managing the deployment?

**Comment by gaby2300** [comment] 2019-08-06 14:06
Could this be related to the following: https://github.com/mozilla/FirefoxColor/issues/815?

**Comment by shmediaproductions** [comment] 2019-08-07 02:26
^Yeah it's definitely the same situation. It used to be that inactive tabs were colored according to the color the user defined for "background color." So in some sense the extension never provided granular control over the inactive tabs, but now it doesn't color them at all.

**Comment by rpl** [comment] 2019-08-07 13:07
This should be a duplicate of #763, it looks like the same issue reported on bugzilla as [Bug 1568068](https://bugzilla.mozilla.org/show_bug.cgi?id=1568068).

**Comment by caitmuenster** [comment] 2019-08-07 15:23
Closing this out as a duplicate.

**Closed by caitmuenster** 2019-08-07 15:23 UTC
