### ISSUE TITLE
A theme can be wrongly saved for an indefinite number of times if it contains a custom background image

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/FirefoxColor#510] opened 2018-10-11 14:37 UTC
**[Affected versions]:**
- Firefox 62.0.3 and above

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Firefox Color" add-on (2.0.0) custom built on 10/11/2018 installed.
- Have an image up to 1MB saved to your drive.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and click the "Firefox Color" toolbar button.
2. Click the "Custom backgrounds" tab and upload the image from prerequisites.
3. Click the "Save" button from the top right part of the page multiple times.
4. Observe the behavior.

**[Expected result]:**
- The theme is saved just once regardless the number of times the "Save" button was clicked.

**[Actual result]:**
- The theme is saved and duplicated in the "Saved theme" tab for each time the "Save" button is clicked.

**[Notes]:**
- This issue is reproducible with the TxP version of the "Firefox Color" add-on.
- This issue is not reproducible with the themes that are not containing a custom background image.
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/46811800-237f8a80-cd7c-11e8-88ac-09de55f78e95.gif)

**Comment by lmorchard** [comment] 2018-10-11 17:03
Seems related to / duplicate of #489 ?

**Closed** 2018-10-11 22:57 UTC
Labels: [QA]:Normal issue

**Comment by Softvision-AndreeaCupsa** [comment] 2018-10-12 08:36
I have verified this issue and is no longer reproducible with the latest custom build (10/12/2018) on Windows 10 x64, Mac 10.13.3 and Arch Linux.
